hatchways/team-evergreen

- server/.env
Hi, Olga, pls review the change.
Thanks!
> Add my name to .env file

- server/routes/api/users.js
- server/test/register.validation.spec.js
- server/validation/register.js
From Olga:
- change emailnotfounnd key in users.js to email key 
- passwordincorrect to password 
Changes password length validation to require that it be >= 6 chars.
> Changes validation paramenters or password length and error key names

- README.md
- server/config/db-connect.js
- server/test/db-connect.spec.js
Changed db-connect to conform to mongoose singleton pattern.  Refactored the test in order to deal with any potential timeout issues that might arise.
> Modifies db-connect and unit test 

- package-lock.json
- package.json
- server/.env
Pull dev and run npm install in root directory.
> Prettier Installation

- README.md
Updates README file with info on Prettier.
> Readme file update for Prettier

- client/package.json
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
Reinstalls scripts to start client and server server at the same time.
> Combo start

- client/src/pages/Login.js
- client/src/pages/Signup.js
- client/src/styles/authStyles.js
- server/routes/api/users.js
-Redirect the user to login page in case login failed after registration
-Show error message if token authorization failed on login
-Fixed error in users.js: added createToken function after the user is saved in a database
> Fix signup errors

- .prettierrc
- README.md
Creates a config file to overwrite two defaults.
> Prettier config

- package-lock.json
- package.json
- server/models/Poll.js
- server/models/User.js
- server/test/Poll.spec.js
Update the User model and added the Poll model.
> Poll model

- server/routes/api/users.js
- server/routes/utils/s3Upload.js
Moves s3Upload function into its own utilities module.
> Refactors s3Upload function into its own module.

- server/package-lock.json
- server/package.json
Update node packages in the server directory to latest versions as there were conflicts when trying to add busboy and aws-sdk.
> Updates npm packages for file upload.

- server/models/friendList.js
- server/routes/api/users.js
- server/validation/friendList.js
-Add new list to Lists table and push new list id to relevant User lists array
-Retrieve all lists for a specific user (can be reused for polls too)
> Friend list route

- client/src/components/AddFriendList.js
- server/routes/api/users.js
Tested integration with add_friend_list route
Users list will be passed from Profile page (will not work unless Profile page is pushed to dev too)
> Friend list integration

- server/routes/api/users.js
-Add options to populate() method in get_user_data to be able to retrieve friends' details for lists
-Same for the route /user/:id
> Fix user route

- client/src/components/AddPollDialog.js
- client/src/components/PollCard.js
- client/src/pages/Profile.js
- server/config/db-connect.js
- server/routes/api/upload.js
- server/routes/utils/pollModelUpdates.js
- server/routes/utils/userModelUpdates.js
- server/routes/utils/voteModelUpdates.js
- server/test/db-connect.spec.js
I fixed the error messages and set the create button to disable on submit.  Still working on the spinner.
> Poll dialog fixes

- client/src/components/AddFriendList.js
- server/routes/api/users.js
-Check list title for uniqueness before saving it in database
-Add 'Select all' option for friends list
-Limit friends list height
-Trim list title before sending it to database
> Improve list dialog

- server/helpers/seeddb.js
- server/models/User.js
Adds friends list to user model.  Changes friends list to remove unique parameter as it was hanging during data load.
> Db seeding update

- client/src/App.js
- client/src/actions.js
- client/src/components/AppNavbar.js
- client/src/components/EditProfileDialog.js
- client/src/components/UserPanel.js
- client/src/constants.js
- client/src/pages/Friends.js
- client/src/pages/FriendsPolls.js
- client/src/pages/PollPage.js
- client/src/pages/Profile.js
- client/src/reducers.js
- client/src/utils/editUserData.js
- Add global action updateUserDataInState to update user details in redux state
- Reset user details when closing edit profile dialog both on cancel and on pressing the X button
- Add error message if bad request received from the server
> EditProfileDialog improvements

- client/README.md
- client/src/App.js
- client/src/actions.js
- client/src/components/AddFriendList.js
- client/src/components/AddPollDialog.js
- client/src/components/AppNavbar.js
- client/src/components/EditProfileDialog.js
- client/src/components/PollSnackbar.js
- client/src/components/UserPanel.js
- client/src/constants.js
- client/src/index.js
- client/src/pages/Friends.js
- client/src/pages/FriendsPolls.js
- client/src/pages/Login.js
- client/src/pages/PollPage.js
- client/src/pages/Profile.js
- client/src/pages/Signup.js
- client/src/reducers.js
- src/routes/api/users.js
Reverts hatchways/team-evergreen#124
> Revert "Fix bugs"

- client/src/components/FriendsDrawer.js
- client/src/pages/FriendsPolls.js
- client/src/pages/Profile.js
- client/src/utils/sortBy.js
- Add sorting function for friends' names
> Friends sort

- client/src/components/PollCard.js
- client/src/pages/Profile.js
- Fix slider controls bug
- Remove console.log from PollCard
> Add unique keys to Box elements to force its  re-render

- client/package-lock.json
- client/src/constants.js
- client/src/utils/setSocketConnection.js
- package-lock.json
- src/bin/www.js
Dynamically sets the websocket server port using the global variable window.location.port when in production.  When in development or test sets port to 3001.
> Dynamically sets websocket server port

- package.json
Fixes:
Websockets not running in production do to wrong ws protocol.  Changes to wss for prod.
> Release Server\Client 1.04\1.0.6

- client/src/constants.js
- client/src/utils/setSocketConnection.js
Sets url of ws server to be public url for app.
> Fix #2 for Production WebSocket Issue

- client/src/App.js
- client/src/actions.js
- client/src/components/FriendsPollCard.js
- client/src/constants.js
- client/src/pages/FriendsPolls.js
- client/src/reducers.js
- remove sorting of friends polls (unnecessary)
- reset friends polls array in the global state on FriendsPolls unmounting
- Revert to class component for FriendsPollCard
- fix voting bug
NB! Please test voting on FriendsPolls page - after reload and after navigating from another page
> Fix real-time voting

- client/src/components/AddPollDialog.js
- client/src/components/AdornedButton.js
- client/src/components/EditProfileDialog.js
Adds a label beneath avatar image with instructions on how to edit.
> Click image to edit

- client/src/components/PollCard.js
Removed React.effect() since there is no other way to fix the React warning
> Transform PollCard into Class component

- client/src/App.js
- client/src/actions.js
- client/src/components/AppNavbar.js
- client/src/components/FriendsDrawer.js
- client/src/components/FriendsList.js
- client/src/components/UserPanel.js
- client/src/constants.js
- client/src/index.js
- client/src/pages/Friends.js
- client/src/pages/FriendsPolls.js
- client/src/pages/PollPage.js
- client/src/pages/Profile.js
- client/src/reducers.js
- Control drawer state with redux
- Create FriendsList component
> Drawer state

- client/package-lock.json
- client/package.json
- client/src/components/FriendsPollCard.js
Built on top of obvious-vote brach -- if you want to test separately test this one second -- otherwise test this one and you will get both.
> Open vote - test after obvious-vote branch

- client/src/components/AddPollDialog.js
- client/src/components/PollCard.js
- src/helpers/seeddb.js
- src/models/Poll.js
- src/routes/api/upload.js
- src/routes/api/users.js
- src/routes/utils/pollModelUpdates.js
- src/routes/utils/voteModelUpdates.js
Makes the following changes:
-  Adds complete fields to Poll Model
-  Adds algorithm to voteModelUpdate to calculate completeness status
-  Updates addPoll module to add complete field on poll create
-  Updates seedDb to include complete poll when creating polls for seed data
-  Polls are now sorted by ( -complete,  -createdAt ) - oldest completed polls show up first, then oldest uncompleted
> Poll complete status

- client/package-lock.json
- client/package.json
- package-lock.json
Audit fixes for npm package vulnerabilities.
> Includes audit fixes.

- src/routes/api/friends.js
- src/routes/api/requests.js
- src/routes/api/results.js
- src/routes/api/vote.js
- src/routes/utils/apiSupport.js
- src/routes/utils/friendManagement.js
Centralizes code to execute data capture requests through one function.  Utilizes dependency injection to separate route call from data query.
> Refactor api request functions

- client/src/components/Slider.js
- client/src/pages/Profile.js
Pass missing props to Slider and EditFriendList component
> Pass props to slider

- client/package-lock.json
- package-lock.json
- package.json
- src/config/db-connect.js
and adds useUnifiedTopology flag to connect string.
> Update mongoose driver to 5.7.5

- client/src/components/AddPollDialog.js
- client/src/components/PollsFilter.js
- client/src/pages/Profile.js
- client/src/styles/profileStyles.js
Add polls filtering to Profile page
> Polls filter
